apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: yas-microservices
  namespace: argocd
spec:
  generators:
    # Dùng Matrix để nhân bản cấu hình thư mục với biến Domain tương ứng
    - matrix:
        generators:
          # Generator 1: Quét các thư mục dịch vụ
          - git:
              repoURL: https://github.com/Thang2005HCMUS/yas
              revision: main
              directories:
                - path: k8s/charts/*
                - path: k8s/charts/Chart.template.yaml
                  exclude: true
                - path: k8s/charts/values.template.yaml
                  exclude: true
                - path: k8s/charts/backend
                  exclude: true
                - path: k8s/charts/ui
                  exclude: true
                - path: k8s/charts/location
                  exclude: true
                - path: k8s/charts/payment
                  exclude: true
                - path: k8s/charts/payment-paypal
                  exclude: true
                - path: k8s/charts/promotion
                  exclude: true
                - path: k8s/charts/rating
                  exclude: true
                - path: k8s/charts/recommendation
                  exclude: true
                - path: k8s/charts/webhook
                  exclude: true
                - path: k8s/charts/yas-configuration
                  exclude: true
          # Generator 2: Định nghĩa các trường hợp đặc biệt cho Ingress Host
          - list:
              elements:
                - appName: backoffice-bff
                  ingressHost: backoffice.yas.local.com
                - appName: storefront-bff
                  ingressHost: storefront.yas.local.com
              # Cấu hình mặc định cho tất cả các service còn lại nếu không khớp tên ở trên
              template:
                ingressHost: api.yas.local.com
  template:
    metadata:
      name: 'yas-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Thang2005HCMUS/yas
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
          parameters:
            # Biến {{ingressHost}} lúc này đã là chuỗi phẳng, sạch sẽ hoàn toàn
            - name: "backend.ingress.host"
              value: "{{ingressHost}}"
            - name: "ingress.host"
              value: "api.yas.local.com"
      destination:
        server: https://kubernetes.default.svc
        namespace: yas
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true