backend:
  image:
    repository: docker.io/23122051/yas-search
    tag: v1.0.0

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: true
  extraEnvFroms:
    - name: SPRING_ELASTICSEARCH_USERNAME
      valueFrom:
        secretKeyRef:
          name: yas-elasticsearch-credentials-secret
          key: ELASTICSEARCH_USERNAME
    - name: SPRING_ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: yas-elasticsearch-credentials-secret
          key: ELASTICSEARCH_PASSWORD
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
