apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  
  groupId: connect-cluster
  offsetStorageTopic: kafka_connect_offsets
  configStorageTopic: kafka_connect_configs
  statusStorageTopic: kafka_connect_status
  
  # QUAN TRỌNG: Dùng image chuẩn của Strimzi làm base để có đủ script chạy
  
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  image: docker.io/my-custom-debezium:latest
  
  # CẤU HÌNH QUAN TRỌNG NHẤT ĐỂ TỰ ĐỘNG PULL:
  # IfNotPresent: Nếu chưa có ở local, nó tự động pull về. Nếu đã có, nó dùng luôn.
  imagePullPolicy: IfNotPresent
  
  template:
    pod:
      # Cung cấp quyền cho Minikube đăng nhập vào Docker Hub để pull
      imagePullSecrets:
        - name: docker-registry.secret
    
