apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "1"
spec:
  image: debezium/connect:2.5.4.Final
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  # Các thuộc tính này BẮT BUỘC phải nằm trực tiếp dưới spec
  groupId: debezium-connect-cluster
  configStorageTopic: debezium-connect-cluster-configs
  offsetStorageTopic: debezium-connect-cluster-offsets
  statusStorageTopic: debezium-connect-cluster-status
  # Các cấu hình phụ khác mới nằm trong mục config
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1