apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
    argocd.argoproj.io/sync-wave: "1"
spec:
  image: debezium/connect:2.5.4.Final
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  config:
    group.id: debezium-connect-cluster
    config.storage.topic: debezium-connect-cluster-configs
    offset.storage.topic: debezium-connect-cluster-offsets
    status.storage.topic: debezium-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    # Bắt buộc thêm các dòng này để Kafka Connect chạy ổn định
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1